### ISSUE TITLE
Install and update broken

### ISSUE THREAD

**Issue by ameturpoet** [marcus-crane/khinsider#30]
When trying to update or install khinsider, I always get the following error in the terminal:

```
==> Fetching marcus-crane/tap/khinsider
==> Downloading https://github.com/marcus-crane/khinsider/releases/download/v0.0
curl: (22) The requested URL returned error: 404

Error: khinsider: Failed to download resource "khinsider"
Download failed: https://github.com/marcus-crane/khinsider/releases/download/v0.0.1/khinsider_0.0.1_darwin_arm64.tar.gz
```

**Comment by marcus-crane** [comment]
Ah! I had accidentally overwritten the Homebrew formula when testing out an unrelated tool.

I'll fix it shortly. Thanks for letting me know 🙂

**Comment by marcus-crane** [comment]
I've reverted the change so this should be working again now
